--INSERT INTO Users (name,email) VALUES ("dan", "dzamora6@ucmerced.edu");
--DELETE FROM Users 
--UPDATE Users SET name="dan" WHERE email= "dan@ucmerced.edu"
--SELECT * FROM Users WHERE email = ""
-- SELECT * FROM Users ORDER BY email